version: "2.2"
networks:
  lnmp:
    driver: bridge
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./project:/var/www
      - ../pro:/var/pro
      - ./nginx/log:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    depends_on:
      - php-fpm
    networks:
      - lnmp
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        - INSTALL_APCU=${INSTALL_APCU}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_PGSQL=${INSTALL_PGSQL}
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ./project:/var/www
      - ../pro:/var/pro
    expose:
      - "9000"
      - "9003"
    networks:
      - lnmp
  posgresql:
    container_name: postgresql
    build:
      context: ./postgresql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: homestead
      POSTGRES_DB: apollo
    networks:
      - lnmp
    expose:
      - "5432"
  redis:
    container_name: redis
    build:
      context: ./redis
    networks:
      - lnmp
    expose:
      - "6379"

